### ISSUE TITLE
Major release every 3 months instead of every 12 weeks

### ISSUE THREAD

**Issue by deepthi** [vitessio/enhancements#2]
We currently do a major release every 12 weeks per VEP-1(#1). I would like to change this to every 3 months / 13 weeks so that the releases are at a more or less fixed time every year.

If we adopt this proposal, 7.0 will be released on July 28, 2020 instead of July 21, 2020.

EDIT:
Another change proposed by @morgo:
Instead of making patch releases monotonic as described [here](https://github.com/vitessio/enhancements/blob/master/veps/vep-1.md#versioning-and-release-cadence), we will modify the versioning to follow SemVer. This is because we have not actually been making weekly releases, we are doing only major releases + on-demand patch releases.
EDIT 2:
Clarify that SemVer is for patch releases. Major version number will change every 3 months.

**Comment by morgo** [comment]
SGTM. I have one other comment: the original intention of monotonic releases was to snapshot release trees weekly and make a release. It's not really panned out that way - we more likely have a known bug that is serious enough we accommodate a patch release for it.

So I think it makes sense to say patch releases are as needed and will follow semver instead.

**Comment by rafael** [comment]
Makes sense to me.

**Comment by guidoiaquinti** [comment]
+1
